### DISCUSSION TITLE
Default for enum

### DISCUSSION THREAD

**Discussion by ribeaud** [encode/django-rest-framework#9297] [Potential Issue]
Hi. After having updated our project to the latest version, we're now having following constructs in the generated `yml`:
```
              status:
                enum:
                - ACTIVE
                - ARCHIVED
                type: string
                default: !!python/object/apply:terminology.models.Status
                - ACTIVE
```
This does not look quite right and causes problems in, i.e., **openapi-generator-cli** which is not able to validate the schema.
What do you think?

Thanks and cheers,

Christian
