### ISSUE TITLE
OpenAPI schema generation missing path component when all paths under a common prefix

### ISSUE THREAD

**Issue by HT154** [encode/django-rest-framework#6675]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Using latest master (ac0f0a177428823c9eeb2a87b8f895ce59b4e7b6)

Root URL config:
```python
# DEFAULT_SCHEMA_CLASS = 'rest_framework.schemas.openapi.AutoSchema'

v1 = [
    path('filter', views.filter), # Simple @api_view with GET only
]

urlpatterns = [
    path('v1/', include(v1)),
#   path('filter', views.filter), # Does not reproduce if this is uncommented or refers to view with schema != None
    path('schema', get_schema_view(authentication_classes=(), permission_classes=(), public=True)), # reproduces with YAML or JSON
]
```

## Expected behavior
Outputs this schema:
```yaml
{
  "openapi": "3.0.2",
  "info": {
    "title": null,
    "version": "TODO"
  },
  "paths": {
    "/v1/filter/": {
      "get": {
        "operationId": "Listfilters",
        "parameters": [],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        }
      }
    }
  }
}
```

## Actual behavior
Outputs this schema:
```yaml
{
  "openapi": "3.0.2",
  "info": {
    "title": null,
    "version": "TODO"
  },
  "paths": {
    "//filter/": { # <- Missing "v1" here
      "get": {
        "operationId": "Listfilters",
        "parameters": [],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        }
      }
    }
  }
}
```
