### ISSUE TITLE
Schema Generator: serializer field from models.DurationField with MinValueValidator produces invalid output

### ISSUE THREAD

**Issue by peterthomassen** [encode/django-rest-framework#8063]
I have a model with the following field:
```python
max_age = models.DurationField(null=True, default=None, validators=[MinValueValidator(timedelta(0))])
```

The schema contains the following output:

```
        max_age:
          type: string
          nullable: true
          minimum: !!python/object/apply:datetime.timedelta
          - 0
          - 0
          - 0
```

This cannot be rendered by Swagger / ReDoc, leading to failures when loading the schema.
