### ISSUE TITLE
Openapi schema generated by `generateschema` does not produces correct types

### ISSUE THREAD

**Issue by microHoffman** [encode/django-rest-framework#8410]
Hello,
I'm using DRF 3.13.1 and `generateschema` for generating the openapi schema that I am using on frontend. Unfortunately either I am doing something wrong, or the types in the schema are not aligned with the types defined in models/serializers. Let me give you two examples. I have this code (simplified):

`models.py`
```py
class AssetContract(BaseModel):
  class Category(models.IntegerChoices):
    ERC20 = 0, "ERC20"
    ERC721 = 1, "ERC721"
    ERC1155 = 2, "ERC1155"

  category = models.IntegerField(choices=Category.choices)
  decimals = models.SmallIntegerField(null=True)
  is_verified = models.BooleanField(default=False)


class Asset(BaseModel):
  @property
  def category(self) -> int:
    return self.contract.category

  @property
  def decimals(self) -> int:
    return self.contract.decimals

  @property
  def is_verified(self) -> bool:
    return self.contract.is_verified


class Offer(BaseModel):
    asset = models.ForeignKey(Asset, on_delete=models.PROTECT)
```
`serializers.py`
```py
ASSET_BASIC_FIELDS = ["address", "category", "decimals", "name", "symbol", "thumbnail_url", "is_verified"]

class ERC20AssetSerializer(serializers.ModelSerializer):
    class Meta:
        model = Asset
        fields = ASSET_BASIC_FIELDS
        read_only_fields = ASSET_BASIC_FIELDS[1:]  # address is not read only

class OfferSerializer(serializers.ModelSerializer):
    asset = ERC20AssetSerializer()

    class Meta:
        model = Offer
        fields = ["asset"]
```
`views.py`
```py
class OfferView(viewsets.ModelViewSet):
    permission_classes = [permissions.AllowAny]
    queryset = Offer.objects.select_related("deed__collateral").all()
    serializer_class = OfferSerializer
    filterset_class = filters.OfferFilter
```

And the generated schema looks like this (shortened version):
```yaml
Offer:
  type: object
  properties:
    asset:
      type: object
      properties:
        category:
          type: string
          readOnly: true
        decimals:
          type: string
          readOnly: true
        is_verified:
          type: string
          readOnly: true
```

I think there are several things wrong with this:
1) Why the `decimals` has a `type: string` in generated schema?
2) Why the `category` has a `type: string` and not just an enum of values (since it is field of type choices).
3) Why the `is_verified` has a `type: string` despite declaring that as boolean?

I'd very appreciate any of your ideas and answers:). Thanks!
